# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [4]:
import pandas as pd
import matplotlib.pyplot as plt 
import requests
import io

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [23]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

response = requests.get(url, verify=False)
chipo = pd.read_csv(io.StringIO(response.text), sep = '\t')

/Users/Shahab/Desktop/VS Code/pandas_exercises/.myexercises/lib/python3.10/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'raw.githubusercontent.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

### Step 4. See the first 10 entries

In [24]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [25]:
# Solution 1
chipo.shape[0]

4622

In [26]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

### Step 6. What is the number of columns in the dataset?

In [27]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [28]:
for col in chipo.columns:
    print(col)

order_id
quantity
item_name
choice_description
item_price

### Step 8. How is the dataset indexed?

In [32]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [62]:
chipo.groupby('item_name')['order_id'].count().sort_values(ascending=False).reset_index().head(1)['item_name']

0    Chicken Bowl
Name: item_name, dtype: object

### Step 10. For the most-ordered item, how many items were ordered?

In [68]:
chipo.groupby('item_name')['order_id'].count().sort_values(ascending=False)[0]

/var/folders/nz/nfl69hpn50z5_frkmdhc8dlw0000gp/T/ipykernel_24653/927098528.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  chipo.groupby('item_name')['order_id'].count().sort_values(ascending=False)[0]

np.int64(726)

### Step 11. What was the most ordered item in the choice_description column?

In [80]:
chipo.groupby('choice_description')['quantity'].sum().sort_values(ascending=False).reset_index()

                                     choice_description  quantity
0                                           [Diet Coke]       159
1                                                [Coke]       143
2                                              [Sprite]        89
3     [Fresh Tomato Salsa, [Rice, Black Beans, Chees...        49
4     [Fresh Tomato Salsa, [Rice, Black Beans, Chees...        42
...                                                 ...       ...
1038  [Roasted Chili Corn Salsa, [Fajita Vegetables,...         1
1039  [Roasted Chili Corn Salsa, [Fajita Vegetables,...         1
1040  [Roasted Chili Corn Salsa, [Fajita Vegetables,...         1
1041  [Roasted Chili Corn Salsa, [Guacamole, Sour Cr...         1
1042  [[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...         1

[1043 rows x 2 columns]

### Step 12. How many items were orderd in total?

In [82]:
chipo['quantity'].sum()

np.int64(4972)

### Step 13. Turn the item price into a float

In [98]:
chipo['item_price'].str[1:-1].astype(float)

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

#### Step 13.a. Check the item price type

In [79]:
chipo['item_price'].isna().sum()

np.int64(0)

In [106]:
chipo['item_price'] = chipo['item_price'].apply(lambda x: str(x))

#### Step 13.b. Create a lambda function and change the type of item price

In [111]:
chipo["item_price"].apply(lambda x: float(x))

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

#### Step 13.c. Check the item price type

In [112]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB

### Step 14. How much was the revenue for the period in the dataset?

In [119]:
chipo['item_price'].sum()

np.float64(34500.16)

### Step 15. How many orders were made in the period?

### Step 16. What is the average revenue amount per order?

In [ ]:
# Solution 1

In [ ]:
# Solution 2

### Step 17. How many different items are sold?

In [120]:
chipo['item_name'].unique()

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos', 'Steak Salad',
       'Chips and Mild Fresh Tomato Salsa', 'Veggie Soft Tacos',
       'Carnitas Salad Bowl', 'Barbacoa Salad Bowl', 'Salad',
       'Veggie Crispy Tacos', 'Veggie Salad', 'Carnitas Salad'],
      dtype=object)

In [121]:
chipo['item_price'].nunique()

78